### ISSUE TITLE
badge_connect.h: No such file or directory

### ISSUE THREAD

**Issue by rhawr** [ElectronicCats/badge-dragonJARCon-2024#3]
Hi, following the steps on https://github.com/ElectronicCats/Minino/issues/12 (using v5.3.1 version of esp-idf) allowed me to compile the MININO firmware.

Then, I follow the documentation here https://github.com/ElectronicCats/badge-dragonJARCon-2024/blob/main/firmware/README.md, set the environment variable export MININO_PATH=/Users/user/Minino/firmware, run make setup and when I run make compile commands and I'm getting a new error when trying to compile the dragonjarcon badge firmware.

```
[1704/1728] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/apps/badge_link/badge_link_module.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/apps/badge_link/badge_link_module.c.obj 
...
/home/d3vjh/badge-dragonJARCon-2024/firmware/main/apps/badge_link/badge_link_module.c:5:10: fatal error: badge_connect.h: No such file or directory
    5 | #include "badge_connect.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

...

ninja: build stopped: subcommand failed.
BUG: component_requirements.py: cannot match original component filename for source component main
ninja failed with exit code 1, output of the command is in the /home/d3vjh/badge-dragonJARCon-2024/firmware/build/log/idf_py_stderr_output_50768 and /home/d3vjh/badge-dragonJARCon-2024/firmware/build/log/idf_py_stdout_output_50768
make: *** [Makefile:14: compile] Error 2

```
This is the /home/d3vjh/badge-dragonJARCon-2024/firmware/build/log/idf_py_stdout_output_50768
[idf_py_stdout_output_50768.txt](https://github.com/user-attachments/files/17443796/idf_py_stdout_output_50768.txt)

https://github.com/ElectronicCats/badge-dragonJARCon-2024/issues/2

**Comment by JahazielLem** [comment]
Hi,

Please ensure that you have run `git submodule update --init --recursive` in the main folder of the repository.

If you see something like this:
![image](https://github.com/user-attachments/assets/14b809e9-961f-48b3-8b56-b230a21b2505)
Then the folder is empty, so execute `git submodule update --init --recursive` from the root directory. After doing this, you should see something like this:
![image](https://github.com/user-attachments/assets/dddd6350-b88f-4fbc-8b0b-b0d4a08f8664)

Once that's done, you can proceed with `make clean` and `make compile`.

**Comment by rhawr** [comment]
Hey!

I wanted to confirm that the recommendation provided in the response worked perfectly. Thank you for your support and assistance. I am now closing this issue.
